name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSB/buildozer-action@master
        id: buildozer

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: waterpurifier-apk
          path: bin/*.apk
          if-no-files-found: error
